"""Add permisos_usuario table

Revision ID: 20241117_0000
Revises: add_documento_conductor
Create Date: 2024-11-17 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20241117_0000'
down_revision = 'add_documento_conductor'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos_usuario',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('puede_leer', sa.Boolean(), nullable=False),
    sa.Column('puede_crear', sa.Boolean(), nullable=False),
    sa.Column('puede_editar', sa.Boolean(), nullable=False),
    sa.Column('puede_eliminar', sa.Boolean(), nullable=False),
    sa.Column('permisos_especiales', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_permiso_usuario_modulo', 'permisos_usuario', ['usuario_id', 'modulo', 'activo'], unique=False)
    op.create_index(op.f('ix_permisos_usuario_activo'), 'permisos_usuario', ['activo'], unique=False)
    op.create_index(op.f('ix_permisos_usuario_modulo'), 'permisos_usuario', ['modulo'], unique=False)
    op.create_index(op.f('ix_permisos_usuario_usuario_id'), 'permisos_usuario', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permisos_usuario_usuario_id'), table_name='permisos_usuario')
    op.drop_index(op.f('ix_permisos_usuario_modulo'), table_name='permisos_usuario')
    op.drop_index(op.f('ix_permisos_usuario_activo'), table_name='permisos_usuario')
    op.drop_index('idx_permiso_usuario_modulo', table_name='permisos_usuario')
    op.drop_table('permisos_usuario')
    # ### end Alembic commands ###
