"""Add empresa_id to Usuario model

Revision ID: b0cb1c215609
Revises: 
Create Date: 2025-11-10 04:50:40.379858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0cb1c215609'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conceptos_tupa',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False, comment='Monto en soles (PEN)'),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True, comment='Null si está vigente indefinidamente'),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_concepto_tupa_vigencia', 'conceptos_tupa', ['vigencia_desde', 'vigencia_hasta', 'activo'], unique=False)
    op.create_index(op.f('ix_conceptos_tupa_activo'), 'conceptos_tupa', ['activo'], unique=False)
    op.create_index(op.f('ix_conceptos_tupa_codigo'), 'conceptos_tupa', ['codigo'], unique=True)
    op.create_index(op.f('ix_conceptos_tupa_id'), 'conceptos_tupa', ['id'], unique=True)
    op.create_table('tipos_autorizacion',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('requisitos_especiales', sa.JSON(), nullable=True, comment='Requisitos adicionales específicos del tipo de autorización'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_autorizacion_codigo'), 'tipos_autorizacion', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_autorizacion_id'), 'tipos_autorizacion', ['id'], unique=True)
    op.create_table('tipos_infraccion',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('gravedad', sa.Enum('LEVE', 'GRAVE', 'MUY_GRAVE', name='gravedad_infraccion'), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('activo', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_infraccion_codigo'), 'tipos_infraccion', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_infraccion_gravedad'), 'tipos_infraccion', ['gravedad'], unique=False)
    op.create_index(op.f('ix_tipos_infraccion_id'), 'tipos_infraccion', ['id'], unique=True)
    op.create_table('usuarios',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.Enum('SUPERUSUARIO', 'DIRECTOR', 'SUBDIRECTOR', 'OPERARIO', 'GERENTE', name='rolusuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usuario_email_activo', 'usuarios', ['email', 'activo'], unique=False)
    op.create_index('idx_usuario_rol_activo', 'usuarios', ['rol', 'activo'], unique=False)
    op.create_index(op.f('ix_usuarios_activo'), 'usuarios', ['activo'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_empresa_id'), 'usuarios', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=True)
    op.create_index(op.f('ix_usuarios_rol'), 'usuarios', ['rol'], unique=False)
    op.create_table('auditoria',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tabla', sa.String(length=100), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('registro_id', sa.String(length=100), nullable=True),
    sa.Column('datos_anteriores', sa.JSON(), nullable=True),
    sa.Column('datos_nuevos', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auditoria_fecha', 'auditoria', ['created_at'], unique=False)
    op.create_index('idx_auditoria_registro', 'auditoria', ['tabla', 'registro_id'], unique=False)
    op.create_index('idx_auditoria_tabla_accion', 'auditoria', ['tabla', 'accion'], unique=False)
    op.create_index('idx_auditoria_usuario_fecha', 'auditoria', ['usuario_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_auditoria_accion'), 'auditoria', ['accion'], unique=False)
    op.create_index(op.f('ix_auditoria_id'), 'auditoria', ['id'], unique=True)
    op.create_index(op.f('ix_auditoria_registro_id'), 'auditoria', ['registro_id'], unique=False)
    op.create_index(op.f('ix_auditoria_tabla'), 'auditoria', ['tabla'], unique=False)
    op.create_index(op.f('ix_auditoria_usuario_id'), 'auditoria', ['usuario_id'], unique=False)
    op.create_table('empresas',
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('gerente_id', sa.UUID(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gerente_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_empresa_gerente_activo', 'empresas', ['gerente_id', 'activo'], unique=False)
    op.create_index('idx_empresa_ruc_activo', 'empresas', ['ruc', 'activo'], unique=False)
    op.create_index(op.f('ix_empresas_activo'), 'empresas', ['activo'], unique=False)
    op.create_index(op.f('ix_empresas_gerente_id'), 'empresas', ['gerente_id'], unique=False)
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=True)
    op.create_index(op.f('ix_empresas_ruc'), 'empresas', ['ruc'], unique=True)
    op.create_table('notificaciones',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('asunto', sa.String(length=500), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('enviada_at', sa.DateTime(), nullable=False),
    sa.Column('leida_at', sa.DateTime(), nullable=True),
    sa.Column('datos_adicionales', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notificacion_tipo_fecha', 'notificaciones', ['tipo', 'enviada_at'], unique=False)
    op.create_index('idx_notificacion_usuario_fecha', 'notificaciones', ['usuario_id', 'enviada_at'], unique=False)
    op.create_index('idx_notificacion_usuario_leida', 'notificaciones', ['usuario_id', 'leida'], unique=False)
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=True)
    op.create_index(op.f('ix_notificaciones_leida'), 'notificaciones', ['leida'], unique=False)
    op.create_index(op.f('ix_notificaciones_tipo'), 'notificaciones', ['tipo'], unique=False)
    op.create_index(op.f('ix_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    op.create_table('autorizaciones_empresas',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo_autorizacion_id', sa.UUID(), nullable=False),
    sa.Column('numero_resolucion', sa.String(length=100), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True, comment='Null si la autorización no tiene vencimiento'),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_autorizacion_id'], ['tipos_autorizacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_resolucion')
    )
    op.create_index('idx_autorizacion_empresa_tipo', 'autorizaciones_empresas', ['empresa_id', 'tipo_autorizacion_id'], unique=False)
    op.create_index('idx_autorizacion_vigente', 'autorizaciones_empresas', ['vigente', 'fecha_vencimiento'], unique=False)
    op.create_index(op.f('ix_autorizaciones_empresas_empresa_id'), 'autorizaciones_empresas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_autorizaciones_empresas_id'), 'autorizaciones_empresas', ['id'], unique=True)
    op.create_index(op.f('ix_autorizaciones_empresas_tipo_autorizacion_id'), 'autorizaciones_empresas', ['tipo_autorizacion_id'], unique=False)
    op.create_index(op.f('ix_autorizaciones_empresas_vigente'), 'autorizaciones_empresas', ['vigente'], unique=False)
    op.create_table('conductores',
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('licencia_numero', sa.String(length=20), nullable=False),
    sa.Column('licencia_categoria', sa.String(length=10), nullable=False, comment='Categoría de licencia (A-I, A-IIa, A-IIb, A-IIIa, A-IIIb, A-IIIc)'),
    sa.Column('licencia_emision', sa.Date(), nullable=False),
    sa.Column('licencia_vencimiento', sa.Date(), nullable=False),
    sa.Column('certificado_medico_numero', sa.String(length=50), nullable=True),
    sa.Column('certificado_medico_vencimiento', sa.Date(), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'HABILITADO', 'OBSERVADO', 'SUSPENDIDO', 'REVOCADO', name='estadoconductor'), nullable=False),
    sa.Column('observaciones', sa.String(length=1000), nullable=True, comment='Observaciones sobre el conductor'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conductor_dni_estado', 'conductores', ['dni', 'estado'], unique=False)
    op.create_index('idx_conductor_empresa_estado', 'conductores', ['empresa_id', 'estado'], unique=False)
    op.create_index('idx_conductor_licencia_estado', 'conductores', ['licencia_numero', 'estado'], unique=False)
    op.create_index('idx_conductor_vencimientos', 'conductores', ['licencia_vencimiento', 'certificado_medico_vencimiento'], unique=False)
    op.create_index(op.f('ix_conductores_certificado_medico_vencimiento'), 'conductores', ['certificado_medico_vencimiento'], unique=False)
    op.create_index(op.f('ix_conductores_dni'), 'conductores', ['dni'], unique=True)
    op.create_index(op.f('ix_conductores_empresa_id'), 'conductores', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_conductores_estado'), 'conductores', ['estado'], unique=False)
    op.create_index(op.f('ix_conductores_id'), 'conductores', ['id'], unique=True)
    op.create_index(op.f('ix_conductores_licencia_numero'), 'conductores', ['licencia_numero'], unique=True)
    op.create_index(op.f('ix_conductores_licencia_vencimiento'), 'conductores', ['licencia_vencimiento'], unique=False)
    op.create_table('asignaciones_vehiculo',
    sa.Column('conductor_id', sa.UUID(), nullable=False),
    sa.Column('placa_vehiculo', sa.String(length=10), nullable=False),
    sa.Column('fecha_asignacion', sa.Date(), nullable=False),
    sa.Column('fecha_desasignacion', sa.Date(), nullable=True),
    sa.Column('activo', sa.String(length=10), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['conductores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asignacion_conductor_activo', 'asignaciones_vehiculo', ['conductor_id', 'activo'], unique=False)
    op.create_index('idx_asignacion_fechas', 'asignaciones_vehiculo', ['fecha_asignacion', 'fecha_desasignacion'], unique=False)
    op.create_index('idx_asignacion_placa_activo', 'asignaciones_vehiculo', ['placa_vehiculo', 'activo'], unique=False)
    op.create_index(op.f('ix_asignaciones_vehiculo_activo'), 'asignaciones_vehiculo', ['activo'], unique=False)
    op.create_index(op.f('ix_asignaciones_vehiculo_conductor_id'), 'asignaciones_vehiculo', ['conductor_id'], unique=False)
    op.create_index(op.f('ix_asignaciones_vehiculo_id'), 'asignaciones_vehiculo', ['id'], unique=True)
    op.create_index(op.f('ix_asignaciones_vehiculo_placa_vehiculo'), 'asignaciones_vehiculo', ['placa_vehiculo'], unique=False)
    op.create_table('habilitaciones',
    sa.Column('conductor_id', sa.UUID(), nullable=False),
    sa.Column('codigo_habilitacion', sa.String(length=50), nullable=False, comment='Código único de habilitación generado automáticamente'),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_REVISION', 'APROBADO', 'OBSERVADO', 'RECHAZADO', 'HABILITADO', name='estadohabilitacion'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True, comment='Observaciones sobre la solicitud'),
    sa.Column('revisado_por', sa.UUID(), nullable=True),
    sa.Column('aprobado_por', sa.UUID(), nullable=True),
    sa.Column('habilitado_por', sa.UUID(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('fecha_revision', sa.DateTime(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_habilitacion', sa.DateTime(), nullable=True),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True, comment='Fecha de vencimiento de la habilitación'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conductor_id'], ['conductores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['habilitado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revisado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_habilitacion_conductor_estado', 'habilitaciones', ['conductor_id', 'estado'], unique=False)
    op.create_index('idx_habilitacion_estado_fecha', 'habilitaciones', ['estado', 'fecha_solicitud'], unique=False)
    op.create_index('idx_habilitacion_vigencia', 'habilitaciones', ['vigencia_hasta', 'estado'], unique=False)
    op.create_index(op.f('ix_habilitaciones_codigo_habilitacion'), 'habilitaciones', ['codigo_habilitacion'], unique=True)
    op.create_index(op.f('ix_habilitaciones_conductor_id'), 'habilitaciones', ['conductor_id'], unique=False)
    op.create_index(op.f('ix_habilitaciones_estado'), 'habilitaciones', ['estado'], unique=False)
    op.create_index(op.f('ix_habilitaciones_id'), 'habilitaciones', ['id'], unique=True)
    op.create_index(op.f('ix_habilitaciones_revisado_por'), 'habilitaciones', ['revisado_por'], unique=False)
    op.create_index(op.f('ix_habilitaciones_vigencia_hasta'), 'habilitaciones', ['vigencia_hasta'], unique=False)
    op.create_table('infracciones',
    sa.Column('conductor_id', sa.UUID(), nullable=False),
    sa.Column('tipo_infraccion_id', sa.UUID(), nullable=False),
    sa.Column('fecha_infraccion', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('entidad_fiscalizadora', sa.String(length=200), nullable=False),
    sa.Column('numero_acta', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Enum('REGISTRADA', 'EN_PROCESO', 'RESUELTA', 'ANULADA', name='estado_infraccion'), nullable=False),
    sa.Column('resolucion', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['conductores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_infraccion_id'], ['tipos_infraccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_infraccion_conductor_fecha', 'infracciones', ['conductor_id', 'fecha_infraccion'], unique=False)
    op.create_index('idx_infraccion_estado_fecha', 'infracciones', ['estado', 'fecha_infraccion'], unique=False)
    op.create_index(op.f('ix_infracciones_conductor_id'), 'infracciones', ['conductor_id'], unique=False)
    op.create_index(op.f('ix_infracciones_estado'), 'infracciones', ['estado'], unique=False)
    op.create_index(op.f('ix_infracciones_fecha_infraccion'), 'infracciones', ['fecha_infraccion'], unique=False)
    op.create_index(op.f('ix_infracciones_id'), 'infracciones', ['id'], unique=True)
    op.create_index(op.f('ix_infracciones_numero_acta'), 'infracciones', ['numero_acta'], unique=False)
    op.create_index(op.f('ix_infracciones_tipo_infraccion_id'), 'infracciones', ['tipo_infraccion_id'], unique=False)
    op.create_table('pagos',
    sa.Column('habilitacion_id', sa.UUID(), nullable=False),
    sa.Column('concepto_tupa_id', sa.UUID(), nullable=False),
    sa.Column('numero_recibo', sa.String(length=100), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False, comment='Monto pagado en soles (PEN)'),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('entidad_bancaria', sa.String(length=100), nullable=False, comment='Banco o entidad donde se realizó el pago'),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADO', 'RECHAZADO', name='estadopago'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.UUID(), nullable=True),
    sa.Column('fecha_confirmacion', sa.DateTime(), nullable=True),
    sa.Column('confirmado_por', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concepto_tupa_id'], ['conceptos_tupa.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['confirmado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['habilitacion_id'], ['habilitaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pago_concepto_fecha', 'pagos', ['concepto_tupa_id', 'fecha_pago'], unique=False)
    op.create_index('idx_pago_estado_fecha', 'pagos', ['estado', 'fecha_pago'], unique=False)
    op.create_index(op.f('ix_pagos_concepto_tupa_id'), 'pagos', ['concepto_tupa_id'], unique=False)
    op.create_index(op.f('ix_pagos_estado'), 'pagos', ['estado'], unique=False)
    op.create_index(op.f('ix_pagos_fecha_pago'), 'pagos', ['fecha_pago'], unique=False)
    op.create_index(op.f('ix_pagos_habilitacion_id'), 'pagos', ['habilitacion_id'], unique=True)
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=True)
    op.create_index(op.f('ix_pagos_numero_recibo'), 'pagos', ['numero_recibo'], unique=True)
    op.create_index(op.f('ix_pagos_registrado_por'), 'pagos', ['registrado_por'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_registrado_por'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_numero_recibo'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_habilitacion_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_fecha_pago'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_estado'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_concepto_tupa_id'), table_name='pagos')
    op.drop_index('idx_pago_estado_fecha', table_name='pagos')
    op.drop_index('idx_pago_concepto_fecha', table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_infracciones_tipo_infraccion_id'), table_name='infracciones')
    op.drop_index(op.f('ix_infracciones_numero_acta'), table_name='infracciones')
    op.drop_index(op.f('ix_infracciones_id'), table_name='infracciones')
    op.drop_index(op.f('ix_infracciones_fecha_infraccion'), table_name='infracciones')
    op.drop_index(op.f('ix_infracciones_estado'), table_name='infracciones')
    op.drop_index(op.f('ix_infracciones_conductor_id'), table_name='infracciones')
    op.drop_index('idx_infraccion_estado_fecha', table_name='infracciones')
    op.drop_index('idx_infraccion_conductor_fecha', table_name='infracciones')
    op.drop_table('infracciones')
    op.drop_index(op.f('ix_habilitaciones_vigencia_hasta'), table_name='habilitaciones')
    op.drop_index(op.f('ix_habilitaciones_revisado_por'), table_name='habilitaciones')
    op.drop_index(op.f('ix_habilitaciones_id'), table_name='habilitaciones')
    op.drop_index(op.f('ix_habilitaciones_estado'), table_name='habilitaciones')
    op.drop_index(op.f('ix_habilitaciones_conductor_id'), table_name='habilitaciones')
    op.drop_index(op.f('ix_habilitaciones_codigo_habilitacion'), table_name='habilitaciones')
    op.drop_index('idx_habilitacion_vigencia', table_name='habilitaciones')
    op.drop_index('idx_habilitacion_estado_fecha', table_name='habilitaciones')
    op.drop_index('idx_habilitacion_conductor_estado', table_name='habilitaciones')
    op.drop_table('habilitaciones')
    op.drop_index(op.f('ix_asignaciones_vehiculo_placa_vehiculo'), table_name='asignaciones_vehiculo')
    op.drop_index(op.f('ix_asignaciones_vehiculo_id'), table_name='asignaciones_vehiculo')
    op.drop_index(op.f('ix_asignaciones_vehiculo_conductor_id'), table_name='asignaciones_vehiculo')
    op.drop_index(op.f('ix_asignaciones_vehiculo_activo'), table_name='asignaciones_vehiculo')
    op.drop_index('idx_asignacion_placa_activo', table_name='asignaciones_vehiculo')
    op.drop_index('idx_asignacion_fechas', table_name='asignaciones_vehiculo')
    op.drop_index('idx_asignacion_conductor_activo', table_name='asignaciones_vehiculo')
    op.drop_table('asignaciones_vehiculo')
    op.drop_index(op.f('ix_conductores_licencia_vencimiento'), table_name='conductores')
    op.drop_index(op.f('ix_conductores_licencia_numero'), table_name='conductores')
    op.drop_index(op.f('ix_conductores_id'), table_name='conductores')
    op.drop_index(op.f('ix_conductores_estado'), table_name='conductores')
    op.drop_index(op.f('ix_conductores_empresa_id'), table_name='conductores')
    op.drop_index(op.f('ix_conductores_dni'), table_name='conductores')
    op.drop_index(op.f('ix_conductores_certificado_medico_vencimiento'), table_name='conductores')
    op.drop_index('idx_conductor_vencimientos', table_name='conductores')
    op.drop_index('idx_conductor_licencia_estado', table_name='conductores')
    op.drop_index('idx_conductor_empresa_estado', table_name='conductores')
    op.drop_index('idx_conductor_dni_estado', table_name='conductores')
    op.drop_table('conductores')
    op.drop_index(op.f('ix_autorizaciones_empresas_vigente'), table_name='autorizaciones_empresas')
    op.drop_index(op.f('ix_autorizaciones_empresas_tipo_autorizacion_id'), table_name='autorizaciones_empresas')
    op.drop_index(op.f('ix_autorizaciones_empresas_id'), table_name='autorizaciones_empresas')
    op.drop_index(op.f('ix_autorizaciones_empresas_empresa_id'), table_name='autorizaciones_empresas')
    op.drop_index('idx_autorizacion_vigente', table_name='autorizaciones_empresas')
    op.drop_index('idx_autorizacion_empresa_tipo', table_name='autorizaciones_empresas')
    op.drop_table('autorizaciones_empresas')
    op.drop_index(op.f('ix_notificaciones_usuario_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_tipo'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_leida'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_index('idx_notificacion_usuario_leida', table_name='notificaciones')
    op.drop_index('idx_notificacion_usuario_fecha', table_name='notificaciones')
    op.drop_index('idx_notificacion_tipo_fecha', table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_empresas_ruc'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_gerente_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_activo'), table_name='empresas')
    op.drop_index('idx_empresa_ruc_activo', table_name='empresas')
    op.drop_index('idx_empresa_gerente_activo', table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_auditoria_usuario_id'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_tabla'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_registro_id'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_id'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_accion'), table_name='auditoria')
    op.drop_index('idx_auditoria_usuario_fecha', table_name='auditoria')
    op.drop_index('idx_auditoria_tabla_accion', table_name='auditoria')
    op.drop_index('idx_auditoria_registro', table_name='auditoria')
    op.drop_index('idx_auditoria_fecha', table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_usuarios_rol'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_empresa_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_activo'), table_name='usuarios')
    op.drop_index('idx_usuario_rol_activo', table_name='usuarios')
    op.drop_index('idx_usuario_email_activo', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipos_infraccion_id'), table_name='tipos_infraccion')
    op.drop_index(op.f('ix_tipos_infraccion_gravedad'), table_name='tipos_infraccion')
    op.drop_index(op.f('ix_tipos_infraccion_codigo'), table_name='tipos_infraccion')
    op.drop_table('tipos_infraccion')
    op.drop_index(op.f('ix_tipos_autorizacion_id'), table_name='tipos_autorizacion')
    op.drop_index(op.f('ix_tipos_autorizacion_codigo'), table_name='tipos_autorizacion')
    op.drop_table('tipos_autorizacion')
    op.drop_index(op.f('ix_conceptos_tupa_id'), table_name='conceptos_tupa')
    op.drop_index(op.f('ix_conceptos_tupa_codigo'), table_name='conceptos_tupa')
    op.drop_index(op.f('ix_conceptos_tupa_activo'), table_name='conceptos_tupa')
    op.drop_index('idx_concepto_tupa_vigencia', table_name='conceptos_tupa')
    op.drop_table('conceptos_tupa')
    # ### end Alembic commands ###
