"""Initial migration with all models

Revision ID: 28c93c65a4bf
Revises: b0cb1c215609
Create Date: 2025-11-11 10:16:23.586645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c93c65a4bf'
down_revision: Union[str, None] = 'b0cb1c215609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
